baseurl = "https://YsK-dev.github.io"
DefaultContentLanguage = "en"
title = "YsK-dev"
pygmentsStyle = "dracula"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[Params]
  description = "Welcome to my blog"
  mainSections = ["post", "posts"]
  dateFormat = "2006-01-02"
  profilePicture = "img/profile.svg"

[Params.author]
  name = "YsK-dev"
  github = "YsK-dev"

[taxonomies]
  tag = "tags"

[[menu.main]]
    name = "Blog"
    url = "/post/"
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
